baseurl = "https://gitb.vvatanabe.com/"
languageCode = "en-us"
theme = "terminal"
# paginate = 5
hasCJKLanguage = true
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 10
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "gitb"
    subtitle = "A command line tool for using Backlog's git comfortably"
    # keywords = ""
    # copyright = ""
    # menuMore = "Show more"
    # readMore = "Read more"
    # readOtherPosts = "Read other posts"
    languageName = "English"
    languageCode = "en"
    contentDir = "content/en"

    [languages.en.params.logo]
      logoText = "gitb"
      logoHomeLink = "/about"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "install"
        name = "Install"
        url = "/install"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "usage"
        name = "Usage"
        url = "/usage"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "lang"
        name = "日本語"
        url = "/ja/about"
        weight = 4

  [languages.ja]
    title = "gitb"
    subtitle = "BacklogのGitを快適に使うためのコマンドラインツール"
    # keywords = ""
    # copyright = ""
    # menuMore = "Show more"
    # readMore = "Read more"
    # readOtherPosts = "Read other posts"
    languageName = "日本語"
    languageCode = "ja"
    contentDir = "content/ja"

    [languages.ja.params.logo]
      logoText = "gitb"
      logoHomeLink = "/ja/about"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "概要"
        url = "/ja/about"
        weight = 1
      [[languages.ja.menu.main]]
        identifier = "install"
        name = "インストール"
        url = "/ja/install"
        weight = 2
      [[languages.ja.menu.main]]
        identifier = "usage"
        name = "使い方"
        url = "/ja/usage"
        weight = 3
      [[languages.ja.menu.main]]
        identifier = "lang"
        name = "English"
        url = "/about"
        weight = 4
